# -*- coding: utf-8 -*-
"""TrendGraphGen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tNSwqt5lpZzJS7rsyaaBXE_B5AnuBTI-
"""

import matplotlib.pyplot as plt

# %matplotlib inline

import pandas as pd
import numpy as np

X=pd.Series([1,2,3,4,5,6,7,8])

X

y=[]

for element in X:
  y.append(element*element)

y=pd.Series(y)

h=plt.plot(X,y)

h

difffirst=np.diff(y)

y

difffirst

h=np.random.randint(low=30, high=90, size=90)

kkk=pd.DataFrame(h)
kkk.plot(ylim=(0,100),legend=False,figsize=(15,9))
plt.savefig('test2.png')

np.diff(k)

h=np.random.randint(low=70, high=81, size=90)

r=pd.DataFrame(h)

7, 12,  6, 16,  0, 16,  5, 10,  5, 12, 17,  3,  0, 15, 17
plt.savefig('test2.png')

from google.colab import files

files.download('test.png')

files.download('test2.png')

X=np.linspace(23.5,30,num=70)

y=np.sin(X)

plt.plot(X,y)

for i in range(len(X)):
  if(X[i]<0):
    X[i]=0

X

ykok=np.sin(X)

for i in range(len(ykok)):
  if(ykok[i]<0):
    ykok[i]=0

plt.plot(ykok)

X=[i for i in range(1,51)]

X

y=[]

y.append(np.random.randint(low=0, high=20, size=10))

y.append(ykok)

y=[]
y.append(np.random.randint(low=0, high=20, size=65))

y

ykok

for i in range(len(ykok)):
  ykok[i]=int(ykok[i]*100)

ykok

y=[ 6., 15., 24., 33., 42., 50., 58., 66.,
       72., 78., 84., 89., 92., 96., 98., 99., 99., 99., 98., 96., 93.,
       89., 84., 79., 72., 66., 58., 51., 42., 33., 24., 15.]
y1=[-1, -3, -1,  2, -3,  2,  1, -2,  1,  1, -3, -2,  2, -1, -3,  2,  2,
        -3, -2, -3,  0, -1,  2,  1,  2,  0,  1,  0, -3, -3,  1,  1]

for i in range(len(y1)):
  y[i]=y[i]+y1[i]

y

ysin=[15, 14,  9, 18, 17, 18,  1,  4,  6,  9,  5, 17,  4, 13, 13, 17,  8,
         1, 12, 18,  3,  5,  7,  0, 17,  4,  6,  0,  7, 19,  0,  1,  7, 19,
         7, 12,  0,  3, 13, 19,  6, 10,  0,  9,  7,  2, 15, 19,  0,  0, 13,
         3,  8, 12,  9, 12, 11, 17, 15, 18,  2,  7, 15,  4,  7, 5.0,
 12.0,
 23.0,
 35.0,
 39.0,
 52.0,
 59.0,
 64.0,
 73.0,
 79.0,
 81.0,
 87.0,
 94.0,
 95.0,
 95.0,
 97.0,
 97.0,
 96.0,
 96.0,
 93.0,
 93.0,
 88.0,
 86.0,
 80.0,
 74.0,]

len(ysin)

madar=pd.DataFrame(ysin)
madar.plot(ylim=(0,100),legend=False,figsize=(15,9))
plt.savefig('test3.png')

from google.colab import files

files.download('test3.png')

